import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import "./globals.scss";
import Header from "@/ui/header/header";

const spaceMono = Space_Mono({
    weight: ["400", "700"],
    subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "MGSG Trucking Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spaceMono.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
