import type { Metadata } from "next";
import { Titillium_Web } from "next/font/google";
import "./globals.scss";

const spaceMono = Titillium_Web({
    weight: ["400", "600", "700"],
    subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "MGSG Trucking Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spaceMono.className}`}>
        {children}
      </body>
    </html>
  );
}
